# Proximity Trees
This is an algorithm made up by Bart Goethals. It doesn't exist yet. It's bsed on another algorithm created for other purposes.

You can read section 3 of [this paper](https://arxiv.org/pdf/1808.10594.pdf) (skip 3.1).
Lucas, B., Shifaz, A., Pelletier, C., O’Neill, L., Zaidi, N., Goethals, B., ... & Webb, G. I. (2019). Proximity forest: an effective and scalable distance-based classifier for time series. Data Mining and Knowledge Discovery, 33(3), 607-635.

## The model

In [213]:
import numpy as np


class Branch:
    def __init__(self, exemplar, class_label, subtree):
        self.exemplar = exemplar  # An object, if from a node it is closest to this exemplar, it goes to given tree
        self.subtree = subtree  # Should be an internal node or a leaf node

        self.class_label = class_label  # The class label of the leaf node, not required for the algorithm, but might be useful for debuggin


class TreeNode:
    def predict(self, data):
        raise NotImplementedError()

    def print(self, depth):
        raise NotImplementedError()


class InternalNode(TreeNode):
    def __init__(self, data_x, data_y, groups, depth, max_depth):
        assert len(data_x) == len(data_y) == len(groups)
        assert len(data_x) > 0

        depth += 1

        self.measure = lambda x, y: np.linalg.norm(x - y)
        self.branches = []  # Contains internal nodes or leaf nodes

        exemplars = get_split(data_x, data_y, groups)

        closest_exemplars = get_closest_exemplars(exemplars, data_x, self.measure)
        for i, exemplar in enumerate(exemplars):
            # Find the data items that are closest to the exemplar (and thus having i in the closest_exemplars array)
            closest_data_x = data_x[closest_exemplars == i]
            closest_data_y = data_y[closest_exemplars == i]
            closest_data_groups = groups[closest_exemplars == i]

            if len(closest_data_x) == 0:
                # If everything is closer to the other one, you don't need to create a node with 0 data points
                continue

            subtree = get_node(closest_data_x, closest_data_y, closest_data_groups, depth, max_depth)
            self.branches.append(Branch(exemplar, i, subtree))  # TODO: Fix label somewhere here instead of i

    def predict(self, data):
        # Return the label of the closest subtree to the data point
        exemplar_distance = [self.measure(data, branch.exemplar) for branch in self.branches]
        closest_exemplars = get_closest_exemplars(exemplar_distance, [data], self.measure)
        branch = self.branches[closest_exemplars[0]]
        return branch.subtree.predict(data)

    def print(self, depth):
        for branch in self.branches:
            print(f"{'-' * depth}Exemplar ({branch.class_label}): " + str(branch.exemplar))
            branch.subtree.print(depth + 1)


# if all data reaching a node has the same class (node is pure), create_leaf function creates a new leaf node and assigns this class lbel to its field class
class LeafNode(TreeNode):
    def __init__(self, class_label):
        self.class_label = class_label  # This label is assigned to all data reaching this node

    def predict(self, data):
        return self.class_label

    def print(self, depth):
        print(f"{'-' * depth}Leaf ({self.class_label})")

In [214]:

# Splitting criteriaa
class ProximityTreeClassifier:
    def __init__(self, max_depth=5):
        self.root = None
        self.max_depth = max_depth

    def fit(self, data_x, data_y, groups):
        self.root = get_node(data_x, data_y, groups, depth=0, max_depth=self.max_depth)
        self.num_features = data_x.shape[1]
        return self

    def predict(self, data):
        # Convert data to numpy array if not yet the case
        if not isinstance(data, np.ndarray):
            data = np.array(data)
        # If data is 1d, add a dimension to make it 2d
        if data.ndim == 1:
            data = data[np.newaxis, :]
        assert self.root is not None, "You must fit the model before predicting"
        assert data.shape[
                   1] == self.num_features, "The number of features in the data must match the number of features in the training data"
        predictions = np.apply_along_axis(self.root.predict, 1, data)
        assert predictions.shape[0] == data.shape[0], "The number of predictions must match the number of data points"
        return predictions

    def print(self):
        self.root.print(0)

In [215]:
def is_pure(data_y):
    # Check if all data has the same class label
    unique_y = np.unique(data_y)
    return len(unique_y) == 1

def get_most_common_element(array):
    return np.argmax(np.bincount(array))

def get_node(data_x, data_y, groups, depth, max_depth):
    assert len(data_x) == len(data_y) == len(groups)
    assert len(data_x) > 0

    if is_pure(data_y) or depth >= max_depth:
        # class_label = data_y.iloc[0] # must use iloc here to get element of first row and not element at index 0
        class_label = get_most_common_element(data_y)
        return LeafNode(class_label)
    else:
        return InternalNode(data_x, data_y, groups, depth, max_depth)


# Some util functions
def random_pick_row(data):
    return data[np.random.randint(0, data.shape[0])]
    # return np.random.choice(group_x_with_label) # Can't use this for 2d arrays


def get_from_group_if_exists_else_random(group_x, group_y, data_x, data_y, label):
    # Get all elements of group_x where group_y == label
    group_x_with_label = group_x[group_y == label]
    if group_x_with_label.size != 0:
        # sample random with same label
        return random_pick_row(group_x_with_label)
    else:
        # If none exist, return a random element from data_x where data_y == label
        data_x_with_label = data_x[data_y == label]
        return random_pick_row(data_x_with_label)


def get_split(data_x, data_y, groups):
    assert len(data_x) == len(data_y) == len(groups)
    assert len(data_x) != 0

    # Sample uniformly any of the groups
    # Get the unique values in groups
    unique_groups = np.unique(groups)
    random_group = np.random.choice(unique_groups)

    # get the elements of data_x and data_y at the indices of the random group
    random_group_indices = np.where(groups == random_group)[0]
    # random_group_x = data_x[random_group_indices]
    # random_group_y = data_y[random_group_indices] # Gave some strange errors, trying take instead
    random_group_x = np.take(data_x, random_group_indices)
    random_group_y = np.take(data_y, random_group_indices)

    assert len(random_group_x) == len(random_group_y) != 0

    exemplar_winner = get_from_group_if_exists_else_random(random_group_x, random_group_y, data_x, data_y, 1)
    exemplar_loser = get_from_group_if_exists_else_random(random_group_x, random_group_y, data_x, data_y, 0)
    exemplars = [exemplar_loser, exemplar_winner]

    return exemplars


def get_distance_to_exemplars(data_x_row, exemplars, measure):
    return [measure(data_x_row, exemplar) for exemplar in exemplars]


def get_closest_exemplars(exemplars, data, measure):
    # Return the index of the exemplar that is closest to the data point
    distances = [get_distance_to_exemplars(data_row, exemplars, measure) for data_row in data]
    closest_exemplar_indices = np.argmin(distances, axis=1)
    assert len(closest_exemplar_indices) == len(data)
    return closest_exemplar_indices


## Test
Just some random data example for debugging

In [207]:
import numpy as np
import matplotlib.pyplot as plt

data_x = np.array([[0, 1, 0], [1, 0, 1], [0, 0, 0],  # 3 headlines for test 0
                   [1, 0, 0], [1, 1, 0], [0, 1, 1]])  # 3 headlines for test 1

data_y = np.array([0, 1, 0,  # test 0
                   1, 0, 0])  # test 1

groups = np.array([0, 0, 0,  # test 0
                   1, 1, 1])  # test 1

In [208]:
model = ProximityTreeClassifier()
model.fit(data_x, data_y, groups)

model.print()

Pure node
Pure node
Pure node
Pure node
Pure node
Pure node
Exemplar (0): 0
-Exemplar (0): 1
--Leaf (0)
-Exemplar (1): [1 0 0]
--Exemplar (0): [0 0 0]
---Exemplar (0): [0 0 0]
----Exemplar (0): 0
-----Leaf (0)
----Exemplar (1): [1 0 0]
-----Leaf (1)
Exemplar (1): 1
-Exemplar (0): [1 1 0]
--Leaf (0)
-Exemplar (1): 1
--Exemplar (0): 0
---Leaf (0)
--Exemplar (1): [1 0 1]
---Leaf (1)


In [188]:
model.predict(data_x)

array([0, 1, 0, 1, 0, 0])

In [189]:
model.predict([[0, 1, 1], [1, 0, 0]])

array([0, 1])

## More test
Let's take a larger test dataset from the real data

In [190]:
from util import get_wpm_train_test, get_manually_labeled_features

train_x, train_y, test_x, test_y, groups = get_wpm_train_test(include_groups=True, x_train_features_only=True,
                                                              full_y_test=True)
test_y_features = get_manually_labeled_features(test_x)

In [191]:
train_x_sm = train_x.head(7).to_numpy()
train_y_sm = train_y.head(7)['Winner'].astype(int).to_numpy()
groups_sm = groups.head(7).to_numpy()
train_x_sm

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0]], dtype=int64)

In [54]:
model = ProximityTreeClassifier()
model.fit(train_x_sm, train_y_sm, groups_sm)
model.print()

Exemplar (0): [0 1 0 0 0 0 0 0 0 0 0 0 1 0 0]
-Exemplar (0): [0 1 0 0 0 0 0 0 0 0 0 0 1 0 0]
--Leaf (0)
-Exemplar (1): [1 1 0 0 1 0 0 0 0 0 0 1 0 0 1]
--Exemplar (0): [1 1 0 0 1 0 0 0 0 0 0 0 0 1 0]
---Leaf (0)
--Exemplar (1): [1 1 0 0 1 0 0 0 0 0 0 1 0 0 1]
---Exemplar (0): [1 1 0 0 1 0 0 0 1 0 0 1 0 0 0]
----Leaf (0)
---Exemplar (1): [1 1 0 0 1 0 0 0 0 0 0 1 0 0 1]
----Leaf (1)
Exemplar (1): [1 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
-Exemplar (0): [1 0 0 0 1 0 0 0 0 0 0 0 1 0 1]
--Leaf (0)
-Exemplar (1): [1 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
--Leaf (1)


In [194]:
# test_x_sm = test_x.head(4).to_numpy()
test_x_features_only = get_manually_labeled_features(test_x.head(4)).to_numpy()
test_y_sm = test_y.head(4)['Winner']
groups_test_sm = test_x.head(4)['Test'].to_numpy()

assert train_x_sm.shape[1] == test_x_features_only.shape[1]  # same number of features

test_x_features_only

array([[0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [196]:
for x, y, group in zip(test_x_features_only, test_y_sm, groups_test_sm):
    prediction = model.predict(x)
    print(f'Test {group} prediction: {prediction}, actual: {y}')

IndexError: list index out of range

This results in all the same predictions (all 0 or all 1) most of the time. (might be just coïncidence, it's also possible to predict the other number):

In [57]:
model.predict([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

array([0])

## Forest

In [ ]:
import pandas as pd


class ProximityForestClassifier:
    def __init__(self, n_trees=10):
        self.n_trees = n_trees
        self.trees = []

    def fit(self, data_x, data_y, groups):
        data_x = self.preprocess_data(data_x)
        data_y = self.preprocess_data(data_y.astype(int))
        groups = self.preprocess_data(groups)

        for i in range(self.n_trees):
            self.trees.append(ProximityTreeClassifier().fit(data_x, data_y, groups))
        return self

    def get_predictions(self, data):
        data = self.preprocess_data(data)
        return [self.trees[i].predict(data) for i in range(self.n_trees)]

    def preprocess_data(self, data):
        # if data is a pandas dataframe, convert to numpy array
        if isinstance(data, pd.DataFrame):
            data = data.replace({True: 1, False: 0})
            data = data.to_numpy()
        return data

    def predict_proba(self, data):
        tree_predictions = self.get_predictions(data)
        return np.mean(tree_predictions, axis=0)

    def predict(self, data):
        tree_predictions = self.get_predictions(data)
        most_occuring = np.apply_along_axis(get_most_common_element, 0, tree_predictions)
        return most_occuring
        # Get most occuring element for each column


In [193]:
def get_most_common_element(array):
    return np.argmax(np.bincount(array))

In [ ]:
model = ProximityForestClassifier()
model.fit(train_x_sm, train_y_sm, groups_sm)
model.predict(test_x_features_only)

## Full dataset

In [217]:
from util import get_wpm_train_test, get_manually_labeled_features

train_x, train_y, test_x, test_y, groups = get_wpm_train_test(include_groups=True, x_train_features_only=True,
                                                              full_y_test=True)
test_x_features = get_manually_labeled_features(test_x)

model = ProximityForestClassifier()
model.fit(train_x, train_y["Winner"], groups)
model.predict_proba(test_x_features)

array([0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0.1, 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0.1, 0.1, 0. , 0.1, 0. ,
       0. , 0. , 0. , 0.1, 0. , 0. , 0.1, 0. , 0. , 0.1, 0. , 0. , 0. ,
       0.1, 0. , 0.1, 0. , 0. , 0.1, 0. , 0. , 0. , 0.1, 0. , 0. , 0.1,
       0.1, 0. , 0. , 0. , 0.1, 0. , 0.1, 0.1, 0. , 0. , 0. , 0.1, 0. ,
       0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0.1, 0. , 0.1, 0. , 0. , 0. ,
       0.1, 0. , 0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0.1, 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0.1, 0.1, 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0.8, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0. ,
       0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0.1, 0.1, 0.1, 0.1, 0. , 0. , 0. , 0. , 0.1, 0.1, 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.